In [3]:
import pandas as pd
import numpy as np

In [4]:
keystroke = pd.read_csv(
    r"C:\Users\navee\PreStrokeNet\Datasets\interim\keystroke_clean.csv"
)

In [5]:
keystroke.head()

   subject  key      H     UD     DD
0        2   44  0.110  0.125  0.235
1        2   42  0.094  0.312  0.406
2        2   42  0.062  0.859  0.921
3        2   42  0.078  0.469  0.547
4        2   42  0.062  0.688  0.750

In [6]:
features = keystroke.groupby("subject").agg({
    "H": ["mean", "std", "min", "max"],
    "UD": ["mean", "std", "min", "max"],
    "DD": ["mean", "std", "min", "max"]
})

In [7]:
features.head()

                H                                UD                           \
             mean       std    min    max      mean       std    min     max
subject
0        0.108812  0.056390  0.015  0.407  0.267724  0.791619  0.000   5.281
1        0.108500  0.022589  0.062  0.141  1.831611  4.935512  0.031  20.469
2        0.097849  0.037219  0.000  0.359  0.523531  1.281336  0.000   9.797
3        0.117646  0.068675  0.000  0.453  0.801951  3.615834  0.000  36.531

               DD
             mean       std    min     max
subject
0        0.376536  0.793164  0.015   5.406
1        1.940111  4.932892  0.125  20.562
2        0.621380  1.278854  0.016   9.891
3        0.919597  3.610514  0.000  36.609

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()
scaled = scaler.fit_transform(features)

In [11]:
scaled_features = pd.DataFrame(
    scaled,
    columns=features.columns,
    index=features.index
)

In [12]:
scaled_features.head()

                H                                      UD                      \
             mean       std       min       max      mean       std       min
subject
0        0.087017  0.576104 -0.167125  0.560184 -0.990708 -1.100407 -0.577350
1        0.042518 -1.338224  1.681082 -1.663831  1.642100  1.345329  1.732051
2       -1.475837 -0.509684 -0.756978  0.158858 -0.560057 -0.811374 -0.577350
3        1.346301  1.271803 -0.756978  0.944788 -0.091335  0.566452 -0.577350

                         DD
              max      mean       std       min       max
subject
0       -1.059195 -0.987610 -1.099193 -0.479473 -1.058177
1        0.203674  1.639166  1.346328  1.718111  0.203544
2       -0.683694 -0.576278 -0.812275 -0.459495 -0.684806
3        1.539216 -0.075278  0.565141 -0.779143  1.539439

In [13]:
scaled_features.to_csv(
    r"C:\Users\navee\PreStrokeNet\Datasets\Processed\keystroke_features_final.csv"
)